spring:
  application:
    name: zentra-api
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 'z&ntr@SIF&N'
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc.time_zone: UTC

server:
  port: 9090
