-- ==============================================================================
-- Diccionario de Errores SIFEN (Tipos XSD)
-- ==============================================================================
-- Este script carga las traducciones de las etiquetas XSD de SIFEN a texto humano.
-- Utiliza ON CONFLICT DO NOTHING para ser idempotente en cada arranque.

INSERT INTO sifen_diccionario_errores (id, codigo_sifen, etiqueta_humana, descripcion, activo) VALUES
(gen_random_uuid()::varchar, 'tdDirec', 'Dirección', 'Tipo de dato para dirección de hasta 255 caracteres.', true),
(gen_random_uuid()::varchar, 'tdNumCas', 'Número de Casa', 'Número de casa o local.', true),
(gen_random_uuid()::varchar, 'tdNombre', 'Razón Social o Nombre', 'Nombre o razón social del contribuyente o cliente.', true),
(gen_random_uuid()::varchar, 'tdPoliza', 'Número de Póliza', 'Número de póliza de seguro.', true),
(gen_random_uuid()::varchar, 'tdDesTipCons', 'Descripción de Tipo de Constancia', 'Descripción del tipo de constancia SIFEN.', true),
(gen_random_uuid()::varchar, 'tCiudad', 'Código de Ciudad', 'Código de la ciudad donde se realiza la transacción.', true),
(gen_random_uuid()::varchar, 'tDesCiudad', 'Nombre de Ciudad', 'Nombre de la ciudad donde se realiza la transacción.', true),
(gen_random_uuid()::varchar, 'tDistrito', 'Código de Distrito', 'Código de distrito SIFEN.', true),
(gen_random_uuid()::varchar, 'tDesDistrito', 'Nombre de Distrito', 'Nombre del distrito SIFEN.', true),
(gen_random_uuid()::varchar, 'tiTipDocAso', 'Tipo de Documento Asociado', 'Tipo de documento impreso o electrónico asociado.', true),
(gen_random_uuid()::varchar, 'tiMotEmi', 'Motivo de Emisión', 'Motivo de emisión de la nota de crédito o débito.', true),
(gen_random_uuid()::varchar, 'noEmptyString', 'Campo de Texto Obligatorio', 'Tipo de dato de cadena que no puede estar vacío.', true),
(gen_random_uuid()::varchar, 'tdNomRec', 'Nombre del Receptor', 'Razón social o nombre del receptor.', true),
(gen_random_uuid()::varchar, 'tdNomEmi', 'Nombre del Emisor', 'Razón social o nombre del emisor.', true),
(gen_random_uuid()::varchar, 'dFeEmiDE', 'Fecha de Emisión', 'Fecha y hora de emisión del documento.', true),
(gen_random_uuid()::varchar, 'dTotGralOpe', 'Total General de la Operación', 'Suma total de la operación (incluye impuestos).', true),
(gen_random_uuid()::varchar, 'dTotIVA', 'Total de IVA', 'Suma total del Impuesto al Valor Agregado.', true),
(gen_random_uuid()::varchar, 'dPUniProSer', 'Precio Unitario', 'Precio unitario del producto o servicio.', true),
(gen_random_uuid()::varchar, 'tdDMotivTras', 'Motivo de Traslado', 'Motivo del traslado para Notas de Remisión.', true),
(gen_random_uuid()::varchar, 'dNomChof', 'Nombre del Chofer', 'Nombre completo del conductor del vehículo.', true),
(gen_random_uuid()::varchar, 'dNumIDChof', 'Nro. Documento del Chofer', 'Número de identificación del conductor.', true),
(gen_random_uuid()::varchar, 'dNroIDVeh', 'Matrícula del Vehículo', 'Número de chapa o matrícula del vehículo de transporte.', true),
(gen_random_uuid()::varchar, 'dDirLocSal', 'Dirección de Salida', 'Dirección del local desde donde parten las mercaderías.', true),
(gen_random_uuid()::varchar, 'dDirLocEnt', 'Dirección de Entrega', 'Dirección del local donde se entregan las mercaderías.', true),
(gen_random_uuid()::varchar, 'dDirChof', 'Dirección del Chofer', 'Dirección de residencia del chofer.', true),
(gen_random_uuid()::varchar, 'dDirRec', 'Dirección del Receptor', 'Dirección física del cliente o receptor.', true),
(gen_random_uuid()::varchar, 'dDirEmi', 'Dirección del Emisor', 'Dirección física del emisor del comprobante.', true),
(gen_random_uuid()::varchar, 'tdEmail', 'Correo Electrónico', 'Dirección de correo electrónico del cliente o receptor.', true),
(gen_random_uuid()::varchar, 'tdTelefono', 'Teléfono', 'Número de teléfono de contacto.', true),
(gen_random_uuid()::varchar, 'tiTipDocRec', 'Tipo de Documento del Receptor', 'Tipo de identificación del receptor (RUC, Cédula, Pasaporte, etc.).', true),
(gen_random_uuid()::varchar, 'dNumIDRec', 'Nro. Documento del Receptor', 'Número de identificación del receptor.', true),
(gen_random_uuid()::varchar, 'tRuc', 'Registro Único de Contribuyente (RUC)', 'Número de RUC (formato sin DV, de 3 a 8 dígitos numéricos).', true),
(gen_random_uuid()::varchar, 'dRucTrans', 'RUC del Transportista', 'RUC de la empresa transportista.', true),
(gen_random_uuid()::varchar, 'iAmb', 'Ambiente', 'Ambiente de SIFEN (1=Pruebas, 2=Producción).', true),
(gen_random_uuid()::varchar, 'iTipEmi', 'Tipo de Emisión', 'Tipo de emisión del documento electrónico.', true),
(gen_random_uuid()::varchar, 'dCodSeg', 'Código de Seguridad', 'Código de seguridad aleatorio del CDC.', true),
(gen_random_uuid()::varchar, 'iTiDE', 'Tipo de Documento Electrónico', 'Código del tipo de documento electrónico (ej. Factura, Nota de Crédito).', true),
(gen_random_uuid()::varchar, 'dNumTim', 'Número de Timbrado', 'Número de timbrado otorgado por la SET.', true),
(gen_random_uuid()::varchar, 'dEst', 'Establecimiento', 'Código del establecimiento (001, 002, etc.).', true),
(gen_random_uuid()::varchar, 'dPunExp', 'Punto de Expedición', 'Código del punto de expedición (001, 002, etc.).', true),
(gen_random_uuid()::varchar, 'dNumDoc', 'Número de Documento', 'Número secuencial del comprobante.', true),
(gen_random_uuid()::varchar, 'dSerieNum', 'Serie del Comprobante', 'Serie del comprobante electrónico.', true),
(gen_random_uuid()::varchar, 'dFeIniT', 'Fecha de Inicio de Timbrado', 'Fecha de vigencia del timbrado.', true),
(gen_random_uuid()::varchar, 'dRucEm', 'RUC del Emisor', 'RUC de la empresa que emite el comprobante.', true),
(gen_random_uuid()::varchar, 'dDVEmi', 'Dígito Verificador del Emisor', 'Dígito verificador del RUC del emisor.', true),
(gen_random_uuid()::varchar, 'iTipCont', 'Tipo de Contribuyente', 'Tipo de contribuyente SIFEN.', true),
(gen_random_uuid()::varchar, 'dNomFanEmi', 'Nombre de Fantasía del Emisor', 'Nombre de fantasía o comercial de la empresa.', true),
(gen_random_uuid()::varchar, 'dCompDir1', 'Complemento de Dirección 1', 'Primer complemento de la dirección.', true),
(gen_random_uuid()::varchar, 'dCompDir2', 'Complemento de Dirección 2', 'Segundo complemento de la dirección.', true),
(gen_random_uuid()::varchar, 'dDesDepEmi', 'Departamento del Emisor', 'Departamento geográfico de la dirección del emisor.', true),
(gen_random_uuid()::varchar, 'dDesDisEmi', 'Distrito del Emisor', 'Distrito de la dirección del emisor.', true),
(gen_random_uuid()::varchar, 'dDesCiuEmi', 'Ciudad del Emisor', 'Ciudad de la dirección del emisor.', true),
(gen_random_uuid()::varchar, 'dTelEmi', 'Teléfono del Emisor', 'Teléfono de contacto de la empresa.', true),
(gen_random_uuid()::varchar, 'dEmailE', 'Email del Emisor', 'Correo electrónico de la empresa emisora.', true),
(gen_random_uuid()::varchar, 'dDenSuc', 'Denominación de la Sucursal', 'Nombre de la sucursal de la empresa.', true),
(gen_random_uuid()::varchar, 'iNatRec', 'Naturaleza del Receptor', 'Naturaleza del receptor del comprobante (Contribuyente, No Contribuyente, Extranjero).', true),
(gen_random_uuid()::varchar, 'iTiOpe', 'Tipo de Operación', 'Tipo de operación (B2B, B2C, B2G).', true),
(gen_random_uuid()::varchar, 'cPaisRec', 'País del Receptor', 'Código del país de residencia del receptor.', true),
(gen_random_uuid()::varchar, 'dDesPaisRe', 'Descripción del País del Receptor', 'Nombre del país del receptor.', true),
(gen_random_uuid()::varchar, 'dNomFanRec', 'Nombre de Fantasía del Receptor', 'Nombre de fantasía del cliente o receptor.', true),
(gen_random_uuid()::varchar, 'dNumCasRec', 'Número de Casa del Receptor', 'Número de casa en la dirección del cliente.', true),
(gen_random_uuid()::varchar, 'dDesDepRec', 'Departamento del Receptor', 'Departamento geográfico de la dirección del cliente.', true),
(gen_random_uuid()::varchar, 'dDesCiuRec', 'Ciudad del Receptor', 'Ciudad de la dirección del cliente.', true),
(gen_random_uuid()::varchar, 'dCodInt', 'Código Interno del Ítem', 'Código interno o SKU del producto.', true),
(gen_random_uuid()::varchar, 'dDesProSer', 'Descripción del Producto o Servicio', 'Nombre o descripción detallada del ítem vendido.', true),
(gen_random_uuid()::varchar, 'cUniMed', 'Unidad de Medida', 'Código de unidad de medida del producto (Unidades, Litros, Kilos, etc.).', true),
(gen_random_uuid()::varchar, 'dCantProSer', 'Cantidad del Ítem', 'Cantidad vendida del producto o servicio.', true),
(gen_random_uuid()::varchar, 'dSubExe', 'Subtotal Exento', 'Suma de los montos exentos del documento.', true),
(gen_random_uuid()::varchar, 'dSub5', 'Subtotal IVA 5%', 'Suma de los montos gravados al 5%.', true),
(gen_random_uuid()::varchar, 'dSub10', 'Subtotal IVA 10%', 'Suma de los montos gravados al 10%.', true),
(gen_random_uuid()::varchar, 'dTotOpe', 'Total de la Operación', 'Monto total de la operación sin descuentos.', true),
(gen_random_uuid()::varchar, 'dTotDesc', 'Total Descuentos', 'Suma total de los descuentos aplicados.', true),
(gen_random_uuid()::varchar, 'iTipTrans', 'Tipo de Transporte', 'Tipo de transporte utilizado en la Nota de Remisión.', true),
(gen_random_uuid()::varchar, 'iModTrans', 'Modalidad de Transporte', 'Modalidad (Terrestre, Fluvial, Aéreo, etc.).', true),
(gen_random_uuid()::varchar, 'iRespFlete', 'Responsable del Flete', 'Sujeto responsable de pagar el costo del flete.', true),
(gen_random_uuid()::varchar, 'dMarVeh', 'Marca del Vehículo', 'Marca del vehículo de transporte.', true),
(gen_random_uuid()::varchar, 'dTipVeh', 'Tipo de Vehículo', 'Clasificación del vehículo utilizado.', true),
(gen_random_uuid()::varchar, 'dNroMatVeh', 'Matrícula del Vehículo', 'Chapa o patente del vehículo.', true),
(gen_random_uuid()::varchar, 'dId', 'Identificador', 'Identificador único (CDC) del documento o evento.', true),
(gen_random_uuid()::varchar, 'dFecFirma', 'Fecha de Firma', 'Fecha y hora de la firma digital.', true),
(gen_random_uuid()::varchar, 'iTiEvt', 'Tipo de Evento', 'Código del tipo de evento.', true),
(gen_random_uuid()::varchar, 'dDesTiEvt', 'Descripción del Evento', 'Descripción o nombre del evento SIFEN.', true)
ON CONFLICT (codigo_sifen) DO NOTHING;
