-- Este archivo fue reemplazado por schema.sql y data.sql.
-- Se mantiene vacío para no romper configuraciones previas que lo referencien.
-- Todos los datos de catálogo ahora están en: modulo-api/src/main/resources/data.sql
-- El DDL de tablas ahora está en:            modulo-api/src/main/resources/schema.sql
